version: 0.2

env:
  variables:
    FRONT_URL: 'http://localhost:8000/'
  parameter-store:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""

phases:
  pre_build:
    commands:
      - echo "Before running tests"
      - cd backend/
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - rm -r .ebextensions
  build:
    commands:
      - echo "Running all unit tests"
      - python manage.py test
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo Build completed on `date`; echo Starting deployment; zappa update dev; else echo Build failed ignoring deployment; fi
      - echo "Deployment completed"