# Generated by Django 3.2 on 2021-05-07 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_open_source',
        ),
        migrations.RemoveField(
            model_name='image',
            name='photographer_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='privacy_consent',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='ImageMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=255)),
                ('is_open_source', models.BooleanField(default=False)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('photographer_name', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_meta', to='basic.image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
