# Generated by Django 2.2.7 on 2019-11-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Tags',
        ),
    ]
