# Generated by Django 3.2 on 2021-05-07 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210507_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='header_image',
        ),
        migrations.AddField(
            model_name='imagemeta',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=8000, validators=[django.core.validators.MaxLengthValidator(8000)]),
        ),
        migrations.AlterField(
            model_name='imagemeta',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.image'),
        ),
    ]
