# Generated by Django 2.2.7 on 2019-11-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20191127_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='Beschreibung',
            new_name='beschreibung',
        ),
    ]
