# Generated by Django 3.2 on 2021-04-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_nextbestheimabend'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextbestheimabend',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
