# Generated by Django 2.2.7 on 2019-11-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20191127_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('beschreibung', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
