# Generated by Django 3.2 on 2021-04-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_nextbestheimabend_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextbestheimabend',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
    ]
