# Generated by Django 2.2.7 on 2019-11-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20191129_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('beschreibung', models.CharField(max_length=60)),
                ('possibleOutside', models.CharField(max_length=7)),
            ],
        ),
    ]
