# Generated by Django 2.2.7 on 2019-11-29 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tag',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='basic.Tag'),
        ),
    ]
