# Generated by Django 2.2.7 on 2019-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20191129_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='event',
            name='possibleOutside',
        ),
        migrations.AddField(
            model_name='event',
            name='isPossibleInside',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='isPossibleOutside',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='material',
            field=models.CharField(default='', max_length=60),
        ),
    ]
