# Generated by Django 3.0 on 2019-12-05 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20191129_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='beschreibung',
        ),
        migrations.AddField(
            model_name='event',
            name='createdBy',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(1000)]),
        ),
        migrations.AddField(
            model_name='event',
            name='executionTimeRating',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='event',
            name='isActive',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='isPrepairationNeeded',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updatedBy',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(40)]),
        ),
    ]
