# Generated by Django 3.0 on 2019-12-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20191205_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='prepairationRating',
        ),
        migrations.AlterField(
            model_name='event',
            name='material',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
