# Generated by Django 3.0 on 2019-12-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20191205_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='beschreibung',
            new_name='description',
        ),
        migrations.AddField(
            model_name='event',
            name='isLvlOne',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='isLvlThree',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='isLvlTwo',
            field=models.BooleanField(default=0),
        ),
    ]
