# Generated by Django 3.0 on 2019-12-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0013_auto_20191208_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='createdBy',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='createdByEmail',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='event',
            name='material',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
