# Generated by Django 3.0 on 2020-03-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0016_auto_20200122_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isPossibleAlone',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='isPossibleDigital',
            field=models.BooleanField(default=0),
        ),
    ]
