# Generated by Django 3.0 on 2020-04-03 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0019_auto_20200328_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=5000, validators=[django.core.validators.MinLengthValidator(75), django.core.validators.MaxLengthValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='material',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
