# Generated by Django 3.0.5 on 2020-05-09 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0022_auto_20200418_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('ordered_id', models.IntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_header', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='basic.TagCategory'),
        ),
    ]
