# Generated by Django 3.0.6 on 2020-05-24 14:43

import basic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_auto_20200509_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=basic.models.nameFile)),
            ],
        ),
    ]
