# Generated by Django 3.1.2 on 2020-11-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0023_auto_20200509_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='ordered_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='is_event_overview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='is_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
